-[wip]

diff --git a/contrib/zjw/scripts/vcpkg-helper b/contrib/zjw/scripts/vcpkg-helper
--- a/contrib/zjw/scripts/vcpkg-helper
+++ b/contrib/zjw/scripts/vcpkg-helper
@@ -2,16 +2,19 @@
 # @author Zachary Wartell
 # @brief a hack script
 #
+# TODO
+#
 # - [someday-maybe] port to python
 #
 # RESOURCES:
 # - https://man7.org/linux/man-pages/man1/getopts.1p.html 
+# - https://medium.com/@Drew_Stokes/bash-argument-parsing-54f3b81a6a8f
 
 VCPKG_ROOT=/c/vkpkg
 LIBRARY=vrpn
 SRC_DIR=0d99f50601-340a543fbb
 
-init()
+init ()
 {
 	# Create temp git repo for facilitating generation of git diff patches
 	pushd "$VCPKG_ROOT/buildtrees/$LIBRARY/src/$SRC_DIR"
@@ -21,36 +24,35 @@ init()
 	popd
 }
 
-generate_patches()
+generate_patches ()
 {
+    echo generate_patches
 	FILES=`git status | grep modified:`
 	echo $FILES
 }
 
-generate_patches
+dry_run=
 
-aflag=
-           bflag=
-           while getopts ab: name
-           do
-               case $name in
-               a)    aflag=1;;
-               b)    bflag=1
-                     bval="$OPTARG";;
-               ?)   printf "Usage: %s: [-a] [-b value] args\n" $0
-                     exit 2;;
-               esac
-           done
-           if [ ! -z "$aflag" ]; then
-               printf "Option -a specified\n"
-           fi
-           if [ ! -z "$bflag" ]; then
-               printf 'Option -b "%s" specified\n' "$bval"
-           fi
-           shift $(($OPTIND - 1))
-           printf "Remaining arguments are: %s\n$*"
-
-
-
-
-
+PARAMS=""
+while (( "$#" )); do
+    case "$1" in
+        --dry-run)
+            dry_run=1
+            shift
+            ;;
+        --generate-patches)
+            generate_patches
+            exit 0
+            ;;
+        -*|--*=) # unsupported flags
+            echo "Error: Unsupported flag $1" >&2
+            exit 1
+            ;;
+        *) # preserve positional arguments
+            PARAMS="$PARAMS $1"
+            shift
+            ;;
+    esac
+done
+# set positional arguments in their proper place
+eval set -- "$PARAMS"
